owner: hickoryhouse
repo: kf

sites:
  - name: Kiwi Farms Forum
    url: https://kiwifarms.net
    icon: https://raw.githubusercontent.com/hickoryhouse/kf/master/assets/favicon.ico
    expectedStatusCodes:
      - 403
      - 200
      - 203
  - name: Sneed, Today! Forum
    url: https://sneed.today/
    icon: https://raw.githubusercontent.com/hickoryhouse/kf/master/assets/favicon.ico
    expectedStatusCodes:
      - 403
      - 200
      - 203
  - name: Kiwi Farms TG Archive
    url: https://tg.josh.rs/
    icon: https://raw.githubusercontent.com/hickoryhouse/kf/master/assets/tg-favicon.png
    expectedStatusCodes:
      - 403
      - 200
      - 203  
  - name: Kiwi Farms Fediverse
    url: https://kiwifarms.cc
  - name: Kiwi FOSS Git
    url: https://git.kiwifarms.net

status-website:
  baseUrl: /kf
  logoUrl: https://raw.githubusercontent.com/hickoryhouse/kf/master/assets/Kiwi_Farms_Logo_Grey_Text.svg
  name: Kiwi Farms Uptime Monitor
  introMessage: This site is not affiliated with nor operated by Kiwi Farms/Lolcow LLC.
  navbar:
    - title: Status
      href: /kf
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night
  favicon: https://raw.githubusercontent.com/hickoryhouse/kf/master/assets/favicon.ico

skipDescriptionUpdate: true
skipTopicsUpdate: true
skipHomepageUpdate: true

workflowSchedule:
  graphs: "10 */6 * * *"
  responseTime: "5 */6 * * *"
  staticSite: "15 */6 * * *"
  summary: "15 */6 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 * * * *"
