owner: hickoryhouse
repo: kf

sites:
  - name: Kiwi Farms Forum
    url: https://kiwifarms.net
    icon: https://raw.githubusercontent.com/hickoryhouse/kfmonitor/master/assets/favicon.ico
    expectedStatusCodes:
      - 403
  - name: Kiwi Farms Fediverse
    url: https://kiwifarms.cc
  - name: Kiwi FOSS Git
    url: https://git.kiwifarms.net

status-website:
  baseUrl: /kf
  logoUrl: favicon: https://raw.githubusercontent.com/hickoryhouse/kfmonitor/master/assets/favicon.ico
  name: Kiwi Farms Uptime Monitor
  introMessage: This site is not affiliated with nor operated by Kiwi Farms/Lolcow LLC.
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
  theme: night
  favicon: https://raw.githubusercontent.com/hickoryhouse/kfmonitor/master/assets/favicon.ico
